# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rover.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\x12\x05rover\"\x19\n\nMapRequest\x12\x0b\n\x03map\x18\x01 \x01(\t\"#\n\x0f\x43ommandsRequest\x12\x10\n\x08\x63ommands\x18\x01 \x01(\t\"%\n\x0eMineNumRequest\x12\x13\n\x0bmine_number\x18\x01 \x01(\x05\"!\n\x0eSuccessRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x0cShareRequest\x12\x0b\n\x03pin\x18\x01 \x01(\x03\"%\n\x08MapReply\x12\x0c\n\x04size\x18\x01 \x01(\t\x12\x0b\n\x03map\x18\x02 \x01(\t\"!\n\rCommandsReply\x12\x10\n\x08\x63ommands\x18\x01 \x01(\t\"\x1c\n\x0cMineNumReply\x12\x0c\n\x04mine\x18\x01 \x01(\t\"\x1f\n\x0cSuccessReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nShareReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xaa\x02\n\nRoverGuide\x12\x30\n\x06GetMap\x12\x11.rover.MapRequest\x1a\x0f.rover.MapReply\"\x00\x30\x01\x12?\n\x0bGetCommands\x12\x16.rover.CommandsRequest\x1a\x14.rover.CommandsReply\"\x00\x30\x01\x12:\n\nGetMineNum\x12\x15.rover.MineNumRequest\x1a\x13.rover.MineNumReply\"\x00\x12\x37\n\x07Success\x12\x15.rover.SuccessRequest\x1a\x13.rover.SuccessReply\"\x00\x12\x34\n\x08SharePIN\x12\x13.rover.ShareRequest\x1a\x11.rover.ShareReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPREQUEST._serialized_start=22
  _MAPREQUEST._serialized_end=47
  _COMMANDSREQUEST._serialized_start=49
  _COMMANDSREQUEST._serialized_end=84
  _MINENUMREQUEST._serialized_start=86
  _MINENUMREQUEST._serialized_end=123
  _SUCCESSREQUEST._serialized_start=125
  _SUCCESSREQUEST._serialized_end=158
  _SHAREREQUEST._serialized_start=160
  _SHAREREQUEST._serialized_end=187
  _MAPREPLY._serialized_start=189
  _MAPREPLY._serialized_end=226
  _COMMANDSREPLY._serialized_start=228
  _COMMANDSREPLY._serialized_end=261
  _MINENUMREPLY._serialized_start=263
  _MINENUMREPLY._serialized_end=291
  _SUCCESSREPLY._serialized_start=293
  _SUCCESSREPLY._serialized_end=324
  _SHAREREPLY._serialized_start=326
  _SHAREREPLY._serialized_end=355
  _ROVERGUIDE._serialized_start=358
  _ROVERGUIDE._serialized_end=656
# @@protoc_insertion_point(module_scope)
